### ISSUE TITLE
Only allow squash merges on repository

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octoclairvoyant#120]
## What feature would you like to have?

Setup this repository so that only squash merges are allowed.

## What problem will be solved by having the feature?

We have a rule that says that feature branches must be up-to-date with `main` before they can be merged into `main`.

There's a button in the GitHub interface that allows contributors to merge the latest `main` branch into their feature branch, clicking on the button creates a new merge commit:

- Merge branch 'main' into chore/remove-future-features-from-readme

By default GitHub's merge/auto-merge button creates a merge commit as well...

So if we do nothing, we will end up with multiple merge commits on our `main` branch.

We can keep our history clean and understandable by only allow squash merges.

## Do you want to help making the feature?

I cannot set this up, but I can link to the docs on where to find this toggle in the interface:

https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by Belco90** [comment]
Mmm, I'm not really sure about this one. It's ok for me to create a merge commit in some situations (or even in general) so I don't want to force squashing all merges.

**Comment by HonkingGoose** [comment]
> Mmm, I'm not really sure about this one. It's ok for me to create a merge commit in some situations (or even in general) so I don't want to force squashing all merges.

Just wanted to let you know about this. You own the repo, so you can choose how to merge. 😄  
I'll close this issue then, as you've made your decision. 😉
