### ISSUE TITLE
Install `renovate-approve` bot to approve Renovate bot PRs

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octoclairvoyant#135]
## What feature would you like to have?

If you want to automerge, you'll need to install the [renovate-approve](https://github.com/apps/renovate-approve) bot into your GitHub account, or stop requiring pull request reviews.

## What problem will be solved by having the feature?

Currently auto-merge will not work, because we require an approving review before a PR can get merged.

## Do you want to help making the feature?

You could install the renovate-approve bot, that will approve the PRs that Renovate bot makes. That way you can still use required reviews for human PRs, and enjoy auto-merge on the Renovate bot PRs.

Relevant quote from the Renovate bot documentation:

> ### Required Pull Request reviews
> 
> If you have mandatory Pull Request reviews then it means Renovate can't automerge its own PR until such a review has happened.
> 
> If you are running the hosted WhiteSource Renovate App on `github.com`, you can also install the helper apps [renovate-approve](https://github.com/apps/renovate-approve) and [renovate-approve-2](https://github.com/apps/renovate-approve-2) and they will mark all automerging Pull Requests by Renovate as approved.
> These approval helper apps are only available for GitHub.

https://docs.renovatebot.com/automerge-configuration/#required-pull-request-reviews

**Comment by Belco90** [comment]
Installed now!
