### ISSUE TITLE
Octoclairvoyant base domain is the homepage

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octoclairvoyant#142]
## What feature would you like to have?

Make the https://octoclairvoyant.vercel.app/ base domain our landing page.

Use something like `https://octoclairvoyant.vercel.app/comparator` to show the repository compare view.
Once a user has selected a repository, we can use the `comparator/?query-string` pattern.

Proposed URL when a repository has been selected:
`https://octoclairvoyant.vercel.app/comparator/?repo=renovatebot%2Frenovate&from=25.38.0&to=latest`

## What problem will be solved by having the feature?

In my wireframes I've removed the about page, on the assumption that we can use https://octoclairvoyant.vercel.app/ as the landing page.

In the current implementation a user will go straight to the repository comparator select screen, without knowing what the site is about. If they land on the homepage first, they can learn what Octoclairvoyant does and the features it has.

## Do you want to help making the feature?

I don't know how to make this change.

~This feature will be a BREAKING CHANGE for the comparator query string URLs that users have shared/bookmarked.~
No it wont, we will redirect end-users, so old saved links will continue working.

**Comment by Belco90** [comment]
It's funny because this was the original behavior! I changed it to current main page behavior, don't remember exactly why.

This would be a breaking change indeed, but I think I could redirect it to `/comparator` keeping the same query string params if some is found. What do you think about that?

**Comment by HonkingGoose** [comment]
> It's funny because this was the original behavior! I changed it to current main page behavior, don't remember exactly why.

Maybe you changed it because of issue https://github.com/Belco90/octoclairvoyant/issues/25? PR https://github.com/Belco90/octoclairvoyant/pull/27 seems related?

---

> This would be a breaking change indeed, but I think I could redirect it to `/comparator` keeping the same query string params if some is found. What do you think about that?

I don't really understand what this means, can you explain some more?

**Comment by Belco90** [comment]
> > It's funny because this was the original behavior! I changed it to current main page behavior, don't remember exactly why.
> 
> Maybe you changed it because of issue #25? PR #27 seems related?

Not really. At that point, the main page was the comparator itself already. I think it was more a personal preference when I started coding the project.

> > This would be a breaking change indeed, but I think I could redirect it to `/comparator` keeping the same query string params if some is found. What do you think about that?
> 
> I don't really understand what this means, can you explain some more?

Sure. The breaking change it's due to some saved/bookmarked URL. Let's say I have this URL saved: https://octoclairvoyant.vercel.app/?repo=renovatebot%2Frenovate&from=24.96.0&to=25.38.0

As you pointed out, saved URLs have some query strings indicating the repo, from, or to versions (in different combinations). My proposal is to redirect to `/comparator` if any of those query strings are found in the URL. Following this proposal, we would have:
- access to `/` --> user lands in "about" page
- access to `/comparator` --> user lands in "comparator" page with empty form
- access to `/comparator?repo=renovatebot%2Frenovate&from=24.96.0&to=25.38.0` --> user lands in "comparator" page with prefilled form (as now but in the new URL)
- **(this is the breaking change)** access to `/?repo=renovatebot%2Frenovate&from=24.96.0&to=25.38.0` --> user gets redirected to `/comparator?repo=renovatebot%2Frenovate&from=24.96.0&to=25.38.0`

I hope this example helps to get a better understanding of my proposal.

**Comment by HonkingGoose** [comment]
> - access to `/` --> user lands in "about" page

That would be great for now, as I just improved the about page, and it makes more sense to land on the homepage instead of straight into the app. How hard is it to redirect to the "real proper homepage", once we have that ready to go?

> - access to `/comparator` --> user lands in "comparator" page with empty form

Good!

> - access to `/comparator?repo=renovatebot%2Frenovate&from=24.96.0&to=25.38.0` --> user lands in "comparator" page with prefilled form (as now but in the new URL)

Good!

> * **(this is the breaking change)** access to `/?repo=renovatebot%2Frenovate&from=24.96.0&to=25.38.0` --> user gets redirected to `/comparator?repo=renovatebot%2Frenovate&from=24.96.0&to=25.38.0`

Just checking here, does this mean that **old** "comparator" links keep working, or does this mean that old links break?
If a user has saved a old link in their bookmarks, can they still use it after this change, or do they need to use the comparator from scratch to create a new link?

**Comment by Belco90** [comment]
> > * access to `/` --> user lands in "about" page
> 
> That would be great for now, as I just improved the about page, and it makes more sense to land on the homepage instead of straight into the app. How hard is it to redirect to the "real proper homepage", once we have that ready to go?

When I said "user lands in about page" I meant in the home page, that being the about content or whatever content we want.

> > * **(this is the breaking change)** access to `/?repo=renovatebot%2Frenovate&from=24.96.0&to=25.38.0` --> user gets redirected to `/comparator?repo=renovatebot%2Frenovate&from=24.96.0&to=25.38.0`
> 
> Just checking here, does this mean that **old** "comparator" links keep working, or does this mean that old links break?
> If a user has saved a old link in their bookmarks, can they still use it after this change, or do they need to use the comparator from scratch to create a new link?

This means I'd apply that redirect to avoid the breaking change for those with old links saved/bookmarked. They wouldn't need to do anything, the web app would redirect them to the new URL automatically without losing any data within querystrings, so old links would work for them transparently.

**Comment by HonkingGoose** [comment]
> Change the content in the root page at any point is not a problem.

Cool! 😄 I was not sure how easy it would be to change the page we show at the root.

> This means I'd apply that redirect to avoid the breaking change for those with old links saved/bookmarked. They wouldn't need to do anything, the web app would redirect them to the new URL automatically without losing any data within querystrings, so old links would work for them transparently.

So for the end-user it shouldn't be a breaking change, as their old links keep working with the redirect. 😄 

Do we consider it a breaking change with regards to our (Octoclairvoyant) versioning? I notice you have some GitHub releases, but I don't know if you follow SemVer or something else?

**Comment by Belco90** [comment]
> Cool! 😄 I was not sure how easy it would be to change the page we show at the root.

To give you an idea: since this web app is using Next.js, each file you'll find under `pages` folder is a React component that represents what will be rendered for that path. For doing the change you ask in this issue, it's a matter of renaming `index.tsx` to `comparator.tsx`, and then `about.tsx` to `index.tsx`. After that, changing their content means just update what's rendered inside them.
 
> So for the end-user it shouldn't be a breaking change, as their old links keep working with the redirect. 😄
> 
> Do we consider it a breaking change with regards to our (Octoclairvoyant) versioning? I notice you have some GitHub releases, but I don't know if you follow SemVer or something else?

I'd say this is not a breaking change technically. Anyway, that versioning you have seen in the releases is not that stick to SemVer and was just a way of letting users using Octoclairvoyant there were new updates, but more in an app-ish way.

**Comment by HonkingGoose** [comment]
> To give you an idea: since this web app is using Next.js, each file you'll find under `pages` folder is a React component that represents what will be rendered for that path. For doing the change you ask in this issue, it's a matter of renaming `index.tsx` to `comparator.tsx`, and then `about.tsx` to `index.tsx`

I tried those steps on a separate Git branch and that all works fine. I don't understand the `next.config.js` redirect stuff, so I'll let you do that! Nice to see that swapping the pages is not that hard.

> I'd say this is not a breaking change technically.

Removed the breaking change label. 😄 

> Anyway, that versioning you have seen in the releases is not that stick to SemVer and was just a way of letting users using Octoclairvoyant there were new updates, but more in an app-ish way.

Ok! 😄

**Comment by HonkingGoose** [comment]
Hi @Belco90, I think it might be easiest if we change the base domain now, before we start working on #152 and #177.
We also need the switch before starting the next round of header component upgrades. 😄

**Comment by Belco90** [comment]
I'll try to sort it out during the week.

**Comment by HonkingGoose** [comment]
I'll label this `status:ready`, so I know we're good to start. 😄 

You can change the label to `status:in-progress` once you start working on it.
