### ISSUE TITLE
Install/import new font Inter into our code

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octoclairvoyant#184]
## What feature would you like to have?

The design uses the Inter font, so our implementation should use Inter as well.
We should only ever use the Inter font, I don't want to use other fonts, if at all possible.

~We can use `@fontsource/inter` to install the font~, or we can use Google Fonts.

We should set things up so that the only font that's ever in use on our app is the Inter font.
I don't want any Chakra-UI prebuild-components to use some other font. 😉 

## What problem will be solved by having the feature?

Makes the text consistent throughout the app, and uses a font designed for reading on a digital screen.

## Do you want to help making the feature?

Ofcourse!

I'm not sure what I would need to change though.

I found references to open sans in these places:

https://github.com/Belco90/octoclairvoyant/blob/41dfc079044f1a88f0f6d7683cb8a814e33f66d2/src/pages/_app.tsx#L10-L11

https://github.com/Belco90/octoclairvoyant/blob/41dfc079044f1a88f0f6d7683cb8a814e33f66d2/src/customTheme.ts#L42-L56

**Comment by Belco90** [comment]
Hey @HonkingGoose! I like the idea of adding this font.

I almost have the migration ready to Next.js which simplifies how to load fonts, so they can just be loaded from Google Fonts and Next.js will optimize them.

I'll point you to the new way of importing fonts when I create the PR for migrating to Next.js 11 so you can give it a try here for the new font.

What do you think?

**Comment by HonkingGoose** [comment]
> I almost have the migration ready to Next.js which simplifies how to load fonts, so they can just be loaded from Google Fonts and Next.js will optimize them.

No need to have a package installed, and Next.js will do the busy work of optimizing the fonts. Great! 😄 

> I'll point you to the new way of importing fonts when I create the PR for migrating to Next.js 11 so you can give it a try here for the new font.

It won't be as easy as "drag and drop" and be done with it... 😄 To make things look nice, we'll still need to use the correct font size, font color and font weight. Still, actually using the Inter font is a good first step to make things better. 😉

**Comment by HonkingGoose** [comment]
Copy/paste review comment for future reference:

> @HonkingGoose This is how you load fonts from Google Font now! Pretty simple since:
> 
>     * you only need to go to https://fonts.google.com, pick the desired font, and copy&paste the corresponding stylesheet link
> 
>     * Next.js will apply corresponding optimizations
> 
>     * [Next.js has its own ESLint rules](https://nextjs.org/docs/basic-features/eslint#eslint-plugin) so it will warn you if it's not set up properly
> 
> 
> After the font is loaded, you need to set it up in Chakra's theme within `customTheme.ts` file. [The default font family options in Chakra are "body", "heading" and "mono"](https://chakra-ui.com/docs/theming/theme#typography), but we can add more if necessary.
