### ISSUE TITLE
Workflow for working on our code for the new design

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octoclairvoyant#198]
I wanted to discuss how we should work together, and how we want to release our new work.

There are two main methods:

- Release in increments to `main`
- Bundle work in a `v2` feature branch and merge into `main` at the end of the work

If we choose a feature branch, we should integrate any changes from the `main` branch in that feature branch. So if Renovate bot updates the `main` branch, we should pull in those changes into our feature branch. This will help prevent a big merge headache at the end, and ensure everything actually works together. 😄 

If we release in increments, we don't have to worry as much about getting behind the `main` branch. But it would mean that the site looks a bit wonky, as some components will look nice, and other will look bad.

Let me know which option you like best! Or if you have an even better method, please tell me! 😄

**Comment by Belco90** [comment]
To keep it simple, I would just release incrementally to `main` branch.

I'm afraid I won't be able to spend more time on the v2 until end of the summer at least.

**Comment by HonkingGoose** [comment]
> To keep it simple, I would just release incrementally to `main` branch.

That's nice and easy! 😄 

> I'm afraid I won't be able to spend more time on the v2 until end of the summer at least.

Thanks for the heads-up! I'll try to be patient then. 😄
