### ISSUE TITLE
Prepare backend so it supports light/dark colors

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octoclairvoyant#240]
## What feature would you like to have?

I have designed a light and dark variant of the Octoclairvoyant site.
I don't know if we can start using light and dark colors right now, or if we need to do more work on the backend first.

I found this documentation from Chakra UI:

https://chakra-ui.com/docs/features/color-mode

## What problem will be solved by having the feature?

Enable us to use dark/light colors on our site.

## Do you want to help making the feature?

I have the designs for light and dark mode ready.
I also designed a toggle for light/dark for desktop and mobile.

**Comment by Belco90** [comment]
This is really easy to enable (I've done it on my website for example), but I'd leave it on hold a bit since I need to switch between light/dark variants in components. Alternatively, we can enable dark mode only on local and review environments but hide it on production.

**Comment by HonkingGoose** [comment]
> This is really easy to enable (I've done it on my website for example),

Cool!

> need to switch between light/dark variants in components

The components will need to have the properties for the light and dark mode on them. I don't yet know how to use Chakra UI to tell the component "Use these properties for light mode, and use these properties for dark mode". So I'll need to research that anyways. 😄 

> Alternatively, we can enable dark mode only on local and review environments but hide it on production.

I don't know what is best/easiest. I'll let you decide. 😉

**Comment by Belco90** [comment]
> The components will need to have the properties for the light and dark mode on them. I don't yet know how to use Chakra UI to tell the component "Use these properties for light mode, and use these properties for dark mode". So I'll need to research that anyways. 😄

If you want to manually set a value depending on light/dark mode active, you can do that with [`useColorModeValue` hook](https://chakra-ui.com/docs/features/color-mode#usecolormodevalue). I'd like to go one step ahead of that and set it in our theme to indicate what's the light value and the dark value, but for now we will need to set that manually with this hook.

**Comment by HonkingGoose** [comment]
We have 4 <body> backgrounds in the Figma design.

From memory (so don't use this as implementation guide):

- Homepage uses `coolGray.50` on light mode
- Homepage uses `coolGray.900` on dark mode
- Comparator uses `coolGray.100` on light mode
- Comparator uses `coolGray.900` on dark mode

So we need to be able to set a body color for each page, and for each mode on that page... 😄

**Comment by Belco90** [comment]
That's doable with the hook I mentioned. Then I can investigate how to set that up automatically at the theme level so we don't have to manually define it per page basics anymore (same strategy as colors: first use them by tokens, then set them by default within the theme).

**Comment by Belco90** [comment]
Ok let me enable the color mode only for local and preview environments, so you can work switching between light and dark mode, while in production we still only have light mode.
