### ISSUE TITLE
Feature request: change URL for easier bookmarking and sharing!

### ISSUE THREAD

**Issue by gr2m** [Belco90/octoclairvoyant#25]
I wonder if you could mutate the path when I select a repository and versions? E.g.

https://octoclairvoyant.vercel.app/probot/probot/v9.0.0...v10.17.2

**Comment by Belco90** [comment]
Yes! It's one of the 2 next features I want to include. I'll give it a try this week.

**Comment by Belco90** [comment]
@gr2m PR created! #27 

There you can find a preview platform to test the shareable urls. It's finally implemented with querystring, but it's the same behavior. I'm doing some tweaks on the loading spinners and blinks meanwhile. Let me know what you think!

**Comment by gr2m** [comment]
works great!

**Comment by Belco90** [comment]
I'll deploy it today then! At some point this week I'll check #26, should be easy now that I have the sharing mechanism.
