### ISSUE TITLE
Move issues templates to issues forms

### ISSUE THREAD

**Issue by Belco90** [Belco90/octoclairvoyant#252]
## What feature would you like to have?
GitHub has released recently a new form format for filling new issues. You have all the info here: https://github.blog/2021-07-13-whats-new-github-changelog-june-2021/#github-issues

## What problem will be solved by having the feature?
With this new format, it is much easier for users to fill in new issues.

## Do you want to help making the feature?
I can't handle it now, but I can give it a try in a couple of weeks if this is still hanging out.

**Comment by HonkingGoose** [comment]
That's really cool! I'll go figure out how to use the new forms feature... 😄

**Comment by Belco90** [comment]
It looks really nice, and _easy_ to build in yaml format. However, it seems there is no way to preview it? That can be painful.

**Comment by HonkingGoose** [comment]
I'm working on the migration now, it's easy enough to get started.

I'll go clone this repo and do the work over there, so we can try the forms for real on a throwaway repo first... 😉
