### ISSUE TITLE
Feature request: add "latest" to "to version"

### ISSUE THREAD

**Issue by gr2m** [Belco90/octoclairvoyant#26]
combined with #25 it would allow me to have a fixed URL that would work as an upgrade guide, no matter from which version an existing user is coming, it would always look like this: https://octoclairvoyant.vercel.app/probot/probot/v9.0.0...latest, or maybe https://octoclairvoyant.vercel.app/probot/probot/v9.0.0 for short?

**Comment by Belco90** [comment]
That's interesting, never thought about picking "latest" no matter what is that one. For being able to do that I need to implement first the other feature I'm planning: paginate versions. This is necessary in case there are more than one version pages between that v.9.0.0 and latest one. This one will take little bit longer then, but definitely on my list!

**Comment by gr2m** [comment]
What would you consider a “page”?

**Comment by Belco90** [comment]
Sorry, I didn't explain myself really well. With page I meant paginating the versions. At the moment I'm requesting only page 1 with first 100 versions so if the "from" one is previous than that, I wouldn't be able to retrieve it properly with the current mechanism.

**Comment by gr2m** [comment]
`@octokit/rest` comes with https://github.com/octokit/plugin-paginate-rest.js, so yo can just do

```js
const releases = await octokit.paginate(octokit.repos.listReleases, { owner, repo, per_page: 100 })
```

see https://octokit.github.io/rest.js/v18#pagination

**Comment by Belco90** [comment]
Oh wow, that's brilliant! I had the pagination bit from octokit/rest pending, but this is really useful. I'm gonna give it a try, this will make the implementation I needed really simple 🚀

**Comment by Belco90** [comment]
Octokit pagination works like a champ, I got it included in the app in 5 minutes! I'm working on shareable links for #25 and then I'll come back to this one for adding the "latest" repository version.

**Comment by Belco90** [comment]
Implemented on #28, you have there a link to give it a try!

**Comment by Belco90** [comment]
This is how the example you mentioned would look: https://octoclairvoyant-git-issue-26.belco.vercel.app/?repo=probot%2Fprobot&from=v9.0.0&to=latest

**Comment by gr2m** [comment]
awesome, this is very cool! Thanks for implementing it Mario!

**Comment by Belco90** [comment]
@gr2m This was the perfect excuse to go back to this side project! Thanks for your ideas and help with pagination. Deploying on production now 🚀
