### ISSUE TITLE
Install sharp for Image Optimization

### ISSUE THREAD

**Issue by Belco90** [Belco90/octoclairvoyant#334]
### What feature would you like to have?

Install `sharp` so Image Optimization works better.

### What problem will this feature solve?

From [Next.js docs](https://nextjs.org/docs/basic-features/image-optimization#loader):

> For a production environment, it is strongly recommended that you install the optional sharp library by running yarn add sharp in your project directory.

### Do you want to help make the feature?

Yes

**Comment by Belco90** [comment]
I think this is finally not necessary. They have clarified this is automatically done when deploying on Vercel platform: https://github.com/vercel/next.js/pull/28476/files

**Comment by HonkingGoose** [comment]
> They have clarified this is automatically done when deploying on Vercel platform: https://github.com/vercel/next.js/pull/28476/files

Even better, we get all of the benefits in our production environment, without having to deal with dependency updates or configuration.
