### ISSUE TITLE
ci: run Prettier on pushes and PRs targeting `main`

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octoclairvoyant#39]
I saw that currently we only run ESLint checks on incoming pull request, but we don't include Prettier in the linting run.

I could include a Prettier step in the current workflow, or I could create a separate workflow file just for Prettier.

Let me know what you like! 😉

**Comment by Belco90** [comment]
I haven't paid too much attention to CI here since I've been the only one working on it 😅 

Anyway, the current workflow does check types, linting, and format [as you can see here](https://github.com/Belco90/octoclairvoyant/blob/main/.github/workflows/ci.yml). I'm not sure if I'm missing something.

**Comment by HonkingGoose** [comment]
Whoops! Turns out the current workflow **does** run Prettier... 🙈 

Copy/paste from GitHub Action file:

```yaml
      - name: Check code base formatting
        run: yarn format:check
 ```

Copy/paste from `package.json` scripts object:
 
 ```json
  "scripts": {
    "format:check": "yarn prettier --check"
    }
```

**Comment by Belco90** [comment]
Exactly! Sorry if that was misleading, as I mentioned I didn't put that attention to CI/workflow/scripts here.

**Comment by HonkingGoose** [comment]
I wasn't reading it properly, so it's my fault for getting confused. 😄
