### ISSUE TITLE
Migrate from Dependabot to Renovatebot

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octoclairvoyant#43]
I can help with migrating this repository to Renovate bot.

I think that would have the following benefits:

- Able to schedule updates when you like
- You can get a PR to update your lockfile weekly (or monthly or whatever schedule you like)
- Ability to automerge PRs if tests pass
- Includes a nice dashboard issue, that you can pin in your issue list, this shows you all pending updates
- You can configure the bot to only give you major type updates when you tick a checkbox in the Dependency Dashboard issue
- The ability to group certain dependencies together (like group `react-dom` and `react` into one)

Drawbacks of using Renovate bot:

- You need to install the Renovate bot app into your account whereas Dependabot is built in into GitHub
- If you have complicated requirements, it can be a bit of work to figure out how to configure the bot properly

I've made a carbon copy of the `octoclairvoyant` repository to test out a basic but nice Renovate bot configuration. If you want to see how that works, I can give you read access so that you can see how it works, and ask questions there. 😄

**Comment by Belco90** [comment]
I'm not happy with Dependabot, and I was willing to give Renovate a try!

I'd love to see it working, thanks for your help!

**Comment by HonkingGoose** [comment]
Link to throwaway repo to try out an configure Renovate bot together: https://github.com/HonkingGoose/octorenovate
