### ISSUE TITLE
Split GitHub Actions into separate parts

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octoclairvoyant#49]
I think it would be nicer and cleaner to have 2 actions:

Action 1: makes a build (basic smoketest)
Action 2: lint all the things

This way when you get a PR from me or from Renovate bot, you can tell which parts are working and which are failing. 😄 

If you want I can make a PR to create some nicer GitHub Action workflows. 😉

**Comment by Belco90** [comment]
Sounds good! Thanks for your improvements, I really appreciate them. I'd like to collaborate more but I'm swamped with work and other personal projects.

**Comment by HonkingGoose** [comment]
I'll go make a PR for you to review then. 😄
