### ISSUE TITLE
Site redesign mockups

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octoclairvoyant#55]
I have some (hopefully good) ideas to improve the looks of the site.

I'm thinking of making a design mockup, with the mockup you get a preview of how good the site could look with some work.

The general idea is "code refactoring" but for the visual style. Things I want to improve include:

- Header
- Badges
- Buttons
- Typography (font, font weight, font size, font color)
- Iconography (Selecting nice icons where needed)
- Visual hierarchy
- Link style
- Simple layout change for about page
- Footer

If you want, I can make a design mock-up, so that you can see a "preview" of my changes.
The implementation of the mockup would be something that you would need to do, as I don't know enough about HTML/CSS/Chakra UI to be competent at changing the code.

Let me know what you think of my idea to refactor the site looks, and if you want me to go ahead and make the mock-up.

**Comment by Belco90** [comment]
Wow, that would be amazing!

Just be aware I'm quite busy at the moment with other projects lately so I wouldn't be able to implement it soon. But definitely something I'm absolutely interested in!

**Comment by HonkingGoose** [comment]
I'll get started then. 😉

**Comment by HonkingGoose** [comment]
I wanted to let you know that I'm working on this, and am making progress!

I have grayscale drafts for:

- Landing page with better text (we will no longer have an about page, as the landing page will fill that role)
- Header
- Footer (vercel badge now integrated into design)
- Repository select screen
- Authorize Octoclairvoyant modal (Login with GitHub)
- Changelog view (with nice sidebar which shows Repository name, from/to version and button to go back to repository select)
- Badges for the GitHub tagged release

I'm deliberately leaving color out of the design for now, so that I can figure out what parts of the interface need emphasis, and what needs to be de-emphasized. I'll add the Octoclairvoyant brand colors back in once the layout and components are in a final shape. 😄

**Comment by Belco90** [comment]
Great, thanks! Looking forward to seeing your design proposal!

**Comment by HonkingGoose** [comment]
@Belco90 How do you feel about me setting up a project board for the redesign? That way we can capture requirements, ideas, progress, etc.

Also, is your email address on your GitHub profile still correct? I'm ready to show you the first wire-frames/mock-ups of the redesign. I'll send an invite to my Figma design workspace, so that you can see what I'm doing. 😄

**Comment by Belco90** [comment]
That's a good idea. I was thinking about moving my internal notes for future improvements to a project board. You are a collaborator now, I think you have permission to create the board so please go ahead!

The email address in my GitHub profile is correct.

**Comment by Belco90** [comment]
I've checked the first mock-ups available at Figma, it's looking great mate! Can't wait to see more and start implementing it.

**Comment by HonkingGoose** [comment]
> I've checked the first mock-ups available at Figma, it's looking great mate! Can't wait to see more and start implementing it.

Cool! I'm glad you like it! 😄 

Did you see the comments I left on the "artboards"? You can use the <kbd>C</kbd> key to view the comments in Figma.
See the Figma docs for more on comments: https://help.figma.com/hc/en-us/articles/360039825314-Getting-started-with-comments

What would be the best place to gather the feedback, on Figma or on the GitHub project board?

**Comment by Belco90** [comment]
> Did you see the comments I left on the "artboards"? You can use the C key to view the comments in Figma.
> See the Figma docs for more on comments: https://help.figma.com/hc/en-us/articles/360039825314-Getting-started-with-comments

Yes! I didn't know I could get the list of comments, pretty convenient. There are few things I had in mind like sticky headers (I think I actually had that in the very first version but I removed it).

> What would be the best place to gather the feedback, on Figma or on the GitHub project board?

That's exactly what I was wondering too. I guess I can leave some comments here and there in Figma, and then we translate final output here?

**Comment by HonkingGoose** [comment]
> There are few things I had in mind like sticky headers (I think I actually had that in the very first version but I removed it).

I couldn't animate a preview of that behavior but the basic idea is that newer headings push the old heading out of the way. It's probably easier to build it in HTML/CSS than to put it in Figma... 😄 

> I guess I can leave some comments here and there in Figma, and then we translate final output here?

For now, I'd like the feedback on Figma with the comment function, as that way the comment is right next to the component(s) we're talking about. Once you start building out components later on, it's probably easiest to use GitHub to discuss the code, etc.

The next steps are probably:

1. Get your initial impressions via Figma
2. Implement changes to design (if needed based on feedback) in Figma.
3. Work on adding color to the components we have now, in Figma.
4. Design other components we also need (I think I got the most important parts of the website now, but please tell me if you really miss something!)

So for now, just adding your thoughts on Figma will be enough to get me started. 😉

**Comment by HonkingGoose** [comment]
The wireframe is finished now. Please give me feedback on the wireframes.

Are there changes you want me to make?
Do you like the visual hierarchy?
Any feedback is welcome.

Do you want me to add branding colors to the wire-frame?

I'll wait for your feedback before continuing.

**Comment by Belco90** [comment]
Hey mate. Sorry, but I didn't have time last week to check the wireframes. I'll do it this week for sure.

**Comment by HonkingGoose** [comment]
> Hey mate. Sorry, but I didn't have time last week to check the wireframes. I'll do it this week for sure.

Thank you for the apology, I understand that real life can get in the way. I'm looking forward to your feedback. 😄

**Comment by HonkingGoose** [comment]
Hi @Belco90 👋 

I'm willing to design 1 viewport for mobile and 1 for the desktop, as that keeps things simple for me. 😄 

I've started work on a basic mobile layout, and I need to know the size of the mobile viewport. 😉 

Please tell me:

- Width of mobile viewport in `px`
- Height of mobile viewport in `px`

**Comment by HonkingGoose** [comment]
We've chosen to start with a design for **iPhone 11 Pro / X** which is:

- `375px` wide
- `812px` high

**Comment by HonkingGoose** [comment]
Hi @Belco90, I'm done designing the mobile screens, and have tidied up the desktop views.

Can you review my work, and tell me what you think of it? I think having comments in Figma is probably easiest for me, as I can see your comment and work on changes from there. 😄 I've locked the Figma sheet, so that I'm not changing things while you're reviewing. 😉

**Comment by Belco90** [comment]
@HonkingGoose absolutely! Thanks for your work. I should have more spare time this week so I'll make sure to take a look at it and leave any feedback there. Thanks again!

**Comment by HonkingGoose** [comment]
I'm closing this issue, as we have enough mockups to get started with. If we need design work for a new feature, we can create a new issue. 😉

**Comment by Belco90** [comment]
Sure! Thanks for the redesign, I think I'll be able to work on that the next month 🙌

**Comment by HonkingGoose** [comment]
> Sure! Thanks for the redesign, I think I'll be able to work on that the next month 🙌

Hooray! 🥳 😄
