### ISSUE TITLE
Version tag badge links to GitHub release

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octoclairvoyant#89]
## Problem

Right now the change log does not provide an easy way to jump to the GitHub tagged release.
We show a badge with the GitHub tagged version, but clicking on this badge does nothing.

The Octoclairvoyant back-end knows about the tagged versions (because it's filing out the badges with the tag version), but we're not surfacing this to the end-user in an easy way.

## New feature

The version badges are links that the user can click on.
When the user click on the version badge, a new browser window opens with a link to the GitHub release for that version.

## Proposed behavior

1. Go to the octoclairvoyant webpage.
2. Enter search string `renovate`.
3. Select the `renovatebot/renovate` repository from the drop-down.
4. Select version, from `24.0.0` to `25.0.0`.
5. Click on the version badge for `25.0.0`.
6. New browser window opens to: https://github.com/renovatebot/renovate/releases/tag/25.0.0

## Further context

I don't know how hard/easy this is to implement? Feel free to close this if this is too much work for you. 😉

**Comment by Belco90** [comment]
Completely agree with this. I had this idea actually in some notes for future improvements, so definitely something to work on. Should be easy to implement.

**Comment by HonkingGoose** [comment]
> I think I'll have time during the week to tackle this one.

Cool! Looking forward to it. 😉
