### ISSUE TITLE
Require PRs to be up-to-date with `main` before merging, plus allow automerge

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octoclairvoyant#99]
## What feature would you like to have?

I'd like to have the repository set up so that pull requests must always be up-to-date with `main` before they can be merged.

The idea is to set the branch protection rules for the `main` branch so that the checkbox "Require branches to be up to date before merging" is ticked.

## What problem will be solved by having the feature?

It's a good idea to integrate changes from `main` often.
This also has the benefit of confirming that changes on `main` are compatible with the changes from the PR.

I recommend also turning on the ability for you to tell GitHub to merge the branch automatically once the test pass.
That way you don't have to wait around for the test suite to pass and then remember to merge manually.

## Do you want to help making the feature?

I'll link to the GitHub docs, for you to review this idea and potentially set up your repo in this way.
[GitHub docs, Managing a branch protection rule](https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule), search for "Require branches to be up to date before merging".

To setup automerge, read the [GitHub docs, automatically merging a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request).

**Comment by Belco90** [comment]
Good idea. Both options enabled now!

**Comment by HonkingGoose** [comment]
> Good idea. Both options enabled now!

Cool, thank you! 😄
